import { useEffect, useState } from 'react'
import { Plus, Sparkles, Trash2, Play, History, Pencil, Power } from 'lucide-react'
import { api } from '../lib/api'
import { useToast } from '../components/ToastProvider'

const empty={name:'',description:'',enabled:true,trigger_entity:'lead',trigger_event:'created',conditions:[],actions:[{type:'create_task',params:{title:'Follow up'}}]}
const actions=['create_task','update_lead','update_customer','update_task','send_email','draft_email']
function ActionRow({a,onChange,onRemove}){ return <div className="rounded-xl border border-border bg-surface-2 p-3 space-y-2"><div className="flex gap-2"><select value={a.type} onChange={e=>onChange({...a,type:e.target.value})} className="flex-1 rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text">{actions.map(x=><option key={x}>{x}</option>)}</select><button onClick={onRemove} className="px-2 text-danger">×</button></div><input value={a.params?.title||''} onChange={e=>onChange({...a,params:{...a.params,title:e.target.value}})} placeholder="Action title / subject" className="w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text" /></div> }
export default function Workflows(){
 const [items,setItems]=useState([]),[history,setHistory]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[ai,setAi]=useState(''),[loading,setLoading]=useState(true); const {showToast}=useToast()
 const load=async()=>{try{const [w,h]=await Promise.all([api.workflows.list(),api.workflows.history()]);setItems(w);setHistory(h)}catch(e){showToast(e.message,'error')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();try{editing?await api.workflows.update(editing,form):await api.workflows.create(form);setEditing(null);setForm(empty);await load();showToast(editing?'Workflow updated':'Workflow created','success')}catch(e){showToast(e.message,'error')}}
 const suggest=async()=>{try{const x=await api.workflows.suggest(ai);setForm(x);setEditing(null);showToast('AI workflow drafted — review before saving','success')}catch(e){showToast(e.message,'error')}}
 const remove=async id=>{if(!confirm('Delete this workflow?'))return;try{await api.workflows.remove(id);load()}catch(e){showToast(e.message,'error')}}
 const edit=w=>{setEditing(w.id);setForm(w)}
 return <div className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
  <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold text-text">Workflows</h2><p className="mt-1 text-sm text-text-muted">Automate repeatable CRM actions with safe triggers and conditions.</p></div><button onClick={()=>{setEditing(null);setForm(empty)}} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-accent to-accent-2 px-4 py-2.5 text-sm font-medium text-white"><Plus size={15}/> New workflow</button></div>
  <div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]">
   <section className="card-surface rounded-2xl p-5"><div className="mb-4 flex items-center gap-2"><Sparkles size={17} className="text-accent-3"/><h3 className="font-semibold text-text">AI workflow builder</h3></div><div className="flex gap-2"><input value={ai} onChange={e=>setAi(e.target.value)} placeholder="e.g. When a lead becomes Qualified, create a high priority follow-up task" className="min-w-0 flex-1 rounded-xl border border-border bg-surface-2 px-3 py-2.5 text-sm text-text"/><button onClick={suggest} disabled={!ai.trim()} className="rounded-xl bg-surface-hover px-4 text-sm font-medium text-text disabled:opacity-40">Generate</button></div></section>
   <section className="card-surface rounded-2xl p-5"><div className="mb-4 flex items-center gap-2"><History size={17} className="text-accent-3"/><h3 className="font-semibold text-text">Execution history</h3></div>{history.length===0?<p className="text-sm text-text-faint">No executions yet.</p>:<div className="space-y-2 max-h-40 overflow-auto">{history.slice(0,8).map(x=><div key={x.id} className="flex justify-between rounded-lg bg-surface-2 p-2 text-xs"><span className="text-text">{x.trigger_entity} · {x.trigger_event}</span><span className={x.status==='failed'?'text-danger':x.status==='success'?'text-success':'text-text-faint'}>{x.status}</span></div>)}</div>}</section>
  </div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]">
   <section className="card-surface rounded-2xl p-5"><h3 className="mb-4 font-semibold text-text">Your workflows</h3>{loading?<p className="text-sm text-text-faint">Loading…</p>:items.length===0?<p className="text-sm text-text-faint">No workflows yet.</p>:<div className="space-y-2">{items.map(w=><div key={w.id} className="flex items-center gap-3 rounded-xl border border-border p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-text">{w.name}</p><p className="text-xs text-text-faint">{w.trigger_entity} · {w.trigger_event} · {w.actions.length} action{w.actions.length>1?'s':''}</p></div><span className={`text-[11px] ${w.enabled?'text-success':'text-text-faint'}`}>{w.enabled?'Active':'Paused'}</span><button onClick={()=>edit(w)} className="text-text-muted hover:text-text"><Pencil size={14}/></button><button onClick={()=>remove(w.id)} className="text-text-muted hover:text-danger"><Trash2 size={14}/></button></div>)}</div>}</section>
   <form onSubmit={save} className="card-surface rounded-2xl p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-text">{editing?'Edit workflow':'Workflow builder'}</h3>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="text-xs text-text-muted">Cancel</button>}</div><div className="grid gap-3 sm:grid-cols-2"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Workflow name" className="rounded-xl border border-border bg-surface-2 px-3 py-2.5 text-sm text-text"/><input value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" className="rounded-xl border border-border bg-surface-2 px-3 py-2.5 text-sm text-text"/><select value={form.trigger_entity} onChange={e=>setForm({...form,trigger_entity:e.target.value,trigger_event:e.target.value==='task'?form.trigger_event:'created'})} className="rounded-xl border border-border bg-surface-2 px-3 py-2.5 text-sm text-text"><option value="lead">Lead</option><option value="customer">Customer</option><option value="task">Task</option></select><select value={form.trigger_event} onChange={e=>setForm({...form,trigger_event:e.target.value})} className="rounded-xl border border-border bg-surface-2 px-3 py-2.5 text-sm text-text"><option value="created">Created</option><option value="updated">Updated</option>{form.trigger_entity==='task'&&<option value="completed">Completed</option>}</select></div><label className="mt-3 flex items-center gap-2 text-sm text-text-muted"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/><Power size={14}/> Enabled</label><div className="mt-5 flex items-center justify-between"><h4 className="text-sm font-semibold text-text">Actions</h4><button type="button" onClick={()=>setForm({...form,actions:[...form.actions,{type:'create_task',params:{}}]})} className="text-xs text-accent-3">+ Add action</button></div><div className="mt-2 space-y-2">{form.actions.map((a,i)=><ActionRow key={i} a={a} onChange={x=>setForm({...form,actions:form.actions.map((v,j)=>j===i?x:v)})} onRemove={()=>setForm({...form,actions:form.actions.filter((_,j)=>j!==i)})}/>)}</div><button className="mt-5 inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-accent to-accent-2 px-4 py-2.5 text-sm font-medium text-white"><Play size={14}/>{editing?'Save changes':'Create workflow'}</button></form>
  </div>
 </div>
}
